version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rootlyhq/rootly-tui

linters:
  enable:
    - bodyclose
    - copyloopvar
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 150
    gocyclo:
      min-complexity: 35
    goconst:
      min-len: 3
      min-occurrences: 4
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - hugeParam
        - rangeValCopy
    nakedret:
      max-func-lines: 30
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - dupl
          - gosec
          - goconst
          - errcheck
          - revive
      - path: 'cmd/'
        linters:
          - gochecknoinits
      - path: 'internal/debug/'
        linters:
          - gochecknoinits
          - gosec
      - path: 'internal/views/'
        linters:
          - goconst
      - path: 'internal/config/'
        linters:
          - errcheck
