version: 2

project_name: rootly-tui

before:
  hooks:
    - go mod tidy

builds:
  - id: rootly-tui
    main: ./cmd/rootly-tui
    binary: rootly-tui
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=netgo
      - -a
      - -v
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: linux
        goarch: arm  # CGO cross-compilation not supported
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    files:
      - README.md
      - LICENSE.txt

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

homebrew_casks:
  - repository:
      owner: rootlyhq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://rootly.com"
    description: "Terminal UI for Rootly incidents and alerts"
    binaries:
      - rootly-tui
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rootly-tui"]
          end

release:
  github:
    owner: rootlyhq
    name: rootly-tui
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
